# Generated by Django 5.2.15 on 2026-06-04 12:53

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("credit_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "bonus_credit",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                ("price_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price_currency", models.CharField(max_length=20)),
                ("alternative_prices", models.JSONField(default=list)),
                ("payment_provider", models.CharField(default="blockchain", max_length=20)),
                ("blockchain_network", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "economy_credit_package",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CreditRecharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("package_code", models.CharField(max_length=64)),
                ("credit_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("expected_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price_currency", models.CharField(max_length=20)),
                ("payment_provider", models.CharField(default="blockchain", max_length=20)),
                ("blockchain_network", models.CharField(blank=True, max_length=20)),
                ("txid", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "economy_credit_recharge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "economy_creditwallet",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="creditwallet_balance_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("balance_before", models.DecimalField(decimal_places=4, max_digits=18)),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=18)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="economy.creditwallet",
                    ),
                ),
            ],
            options={
                "db_table": "economy_credit_ledger",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyRewardClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("claim_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MP", max_length=8)),
                ("ledger_id", models.UUIDField(blank=True, null=True)),
                ("streak_days", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "economy_daily_reward_claim",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "claim_date"), name="daily_reward_once_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "economy_pointwallet",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="pointwallet_balance_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("balance_before", models.DecimalField(decimal_places=4, max_digits=18)),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=18)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="economy.pointwallet",
                    ),
                ),
            ],
            options={
                "db_table": "economy_point_ledger",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
