# Generated by Django 5.2.15 on 2026-06-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditrecharge",
            name="payment_order_no",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
