# Generated by Django 5.2.15 on 2026-06-07 06:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0002_creditrecharge_payment_order_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditRedeemRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MC", max_length=8)),
                ("redeem_method", models.CharField(max_length=40)),
                ("blockchain_network", models.CharField(blank=True, max_length=20)),
                ("account_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "requested"),
                            ("approved", "approved"),
                            ("completed", "completed"),
                            ("rejected", "rejected"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("hold_ledger_id", models.UUIDField(blank=True, null=True)),
                ("refund_ledger_id", models.UUIDField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "db_table": "economy_credit_redeem_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id", "status"], name="idx_redeem_user_status")
                ],
            },
        ),
    ]
