# Generated by Django 5.2.15 on 2026-06-05 02:28

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("actor_display", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("target_display", models.CharField(blank=True, max_length=255)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("request_metadata", models.JSONField(blank=True, null=True)),
                ("severity", models.CharField(default="info", max_length=20)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["actor_id", "occurred_at"], name="idx_audit_actor"),
                    models.Index(
                        fields=["target_type", "target_id", "occurred_at"], name="idx_audit_target"
                    ),
                    models.Index(fields=["action", "occurred_at"], name="idx_audit_action"),
                    models.Index(fields=["correlation_id"], name="idx_audit_correlation"),
                ],
            },
        ),
    ]
