# Generated by Django 5.2.15 on 2026-06-06 08:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("price_amount", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("price_currency", models.CharField(default="USD", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "membership_plan",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("subscription_id", models.UUIDField(blank=True, null=True)),
                ("source", models.CharField(default="purchase", max_length=20)),
                ("source_ref", models.CharField(blank=True, default="", max_length=128)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="membership.membershipplan",
                    ),
                ),
            ],
            options={
                "db_table": "membership_user_membership",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id", "status"], name="idx_membership_user_status")
                ],
            },
        ),
    ]
