# Generated by Django 5.2.15 on 2026-06-07 05:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "pending_payment"),
                            ("paid", "paid"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(max_length=20)),
                ("payment_provider", models.CharField(max_length=20)),
                ("payment_asset", models.CharField(max_length=20)),
                ("payment_order_no", models.CharField(blank=True, max_length=64)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="membership.membershipplan",
                    ),
                ),
            ],
            options={
                "db_table": "membership_order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id", "status"], name="idx_morder_user_status")
                ],
            },
        ),
    ]
