# Generated by Django 5.2.15 on 2026-06-07 15:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_live_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "public"), ("private", "private")],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("ready", "ready"),
                            ("live", "live"),
                            ("ended", "ended"),
                            ("failed", "failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                ("preview_image_url", models.URLField(blank=True)),
                ("snapshot_url", models.URLField(blank=True)),
                ("viewer_count", models.PositiveIntegerField(default=0)),
                ("ant_media_stream_id", models.CharField(blank=True, max_length=128)),
                ("stream_key", models.CharField(blank=True, max_length=255)),
                ("rtmp_url", models.URLField(blank=True)),
                ("hls_url", models.URLField(blank=True)),
                ("websocket_url", models.URLField(blank=True)),
                ("webrtc_publish_config", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="streams",
                        to="content_live.livecategory",
                    ),
                ),
            ],
            options={
                "db_table": "content_live_stream",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["visibility", "status", "created_at"], name="idx_stream_vis_status"
                    ),
                    models.Index(
                        fields=["owner_user_id", "created_at"], name="idx_stream_owner_created"
                    ),
                ],
            },
        ),
    ]
