# Generated by Django 5.2.15 on 2026-06-07 16:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_live", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "text"), ("product", "product"), ("gift", "gift")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("product_id", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="content_live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "content_live_chat_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["stream", "is_active", "created_at"], name="idx_chat_stream_created"
                    )
                ],
            },
        ),
    ]
