# Generated by Django 5.2.15 on 2026-06-07 16:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_live", "0002_chat_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStreamView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=200)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="content_live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "content_live_stream_view",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("dedup_key",), name="uq_live_view_dedup")
                ],
            },
        ),
    ]
