# Generated by Django 5.2.15 on 2026-06-07 17:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_live", "0003_stream_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStreamPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("meow_points", "meow_points"),
                            ("meow_credit", "meow_credit"),
                            ("stripe", "stripe"),
                            ("blockchain", "blockchain"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="content_live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "content_live_stream_payment_method",
                "ordering": ["sort_order", "method"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stream", "method"), name="uq_live_stream_payment_method"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_id", models.UUIDField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="content_live.livestream",
                    ),
                ),
            ],
            options={
                "db_table": "content_live_stream_product",
                "ordering": ["sort_order", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stream", "product_id"), name="uq_live_stream_product"
                    )
                ],
            },
        ),
    ]
