# Generated by Django 5.2.15 on 2026-06-06 07:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="Brandable Platform", max_length=100)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("favicon_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("support_email", models.EmailField(blank=True, default="", max_length=254)),
                ("min_supported_app_version", models.CharField(default="1.0.0", max_length=20)),
                ("force_upgrade_below", models.CharField(blank=True, default="", max_length=20)),
                ("live_enabled", models.BooleanField(default=True)),
                ("drama_enabled", models.BooleanField(default=True)),
                ("commerce_enabled", models.BooleanField(default=True)),
                ("membership_enabled", models.BooleanField(default=True)),
                ("registration_open", models.BooleanField(default=True)),
                (
                    "stripe_publishable_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("terms_url", models.URLField(blank=True, default="")),
                ("privacy_url", models.URLField(blank=True, default="")),
                ("help_url", models.URLField(blank=True, default="")),
            ],
            options={
                "db_table": "platform_config",
            },
        ),
    ]
