# Generated by Django 5.2.15 on 2026-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
