# Generated by Django 5.2.15 on 2026-06-06 12:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_video_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("private", "private"),
                            ("unlisted", "unlisted"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("free", "free"), ("members_only", "members_only")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("preview_seconds", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="content_video.videocategory",
                    ),
                ),
            ],
            options={
                "db_table": "content_video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("content", models.TextField()),
                ("reply_count", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="content_video.videocomment",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content_video.video",
                    ),
                ),
            ],
            options={
                "db_table": "content_video_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="content_video.video",
                    ),
                ),
            ],
            options={
                "db_table": "content_video_like",
            },
        ),
        migrations.CreateModel(
            name="VideoShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="content_video.video",
                    ),
                ),
            ],
            options={
                "db_table": "content_video_share",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=200)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="content_video.video",
                    ),
                ),
            ],
            options={
                "db_table": "content_video_view",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["visibility", "is_active", "created_at"], name="idx_video_vis_created"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["owner_user_id", "created_at"], name="idx_video_owner_created"
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["video", "parent", "created_at"], name="idx_vcomment_video_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="videolike",
            constraint=models.UniqueConstraint(
                fields=("video", "user_id"), name="uq_videolike_video_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.UniqueConstraint(fields=("dedup_key",), name="uq_videoview_dedup"),
        ),
    ]
