# Generated by Django 5.2.15 on 2026-06-05 09:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SellerStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "commerce_seller_store",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("cover_image_url", models.URLField(blank=True)),
                ("price_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price_currency", models.CharField(max_length=20)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_physical", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="commerce.sellerstore",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("buyer_user_id", models.UUIDField(db_index=True)),
                ("product_snapshot", models.JSONField(default=dict)),
                ("shipping_address_snapshot", models.JSONField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=4, max_digits=18)),
                ("platform_fee", models.DecimalField(decimal_places=4, max_digits=18)),
                ("seller_receivable", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "pending_payment"),
                            ("paid", "paid"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("payment_provider", models.CharField(max_length=20)),
                ("payment_asset", models.CharField(max_length=20)),
                ("payment_order_no", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="commerce.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="commerce.sellerstore",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_product_order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="idx_porder_status_created")
                ],
            },
        ),
    ]
