# Generated by Django 5.2.15 on 2026-06-06 11:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_shop_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("recipient_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("street_address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=40)),
                ("country", models.CharField(max_length=2)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "commerce_shipping_address",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(fields=["user_id", "is_default"], name="idx_ship_user_default")
                ],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_cart_item",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "product"), name="uq_cart_user_product"
                    )
                ],
            },
        ),
    ]
