# Generated by Django 5.2.15 on 2026-06-06 11:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0003_cart_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("business_name", models.CharField(max_length=300)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "commerce_seller_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id", "status"], name="idx_sellerapp_user_status")
                ],
            },
        ),
    ]
