# Generated by Django 5.2.15 on 2026-06-06 11:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_seller_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductShipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("carrier", models.CharField(max_length=120)),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("in_transit", "in_transit"),
                            ("delivered", "delivered"),
                        ],
                        default="in_transit",
                        max_length=20,
                    ),
                ),
                ("shipped_note", models.TextField(blank=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "commerce_product_shipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="productorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("paid", "paid"),
                    ("shipping", "shipping"),
                    ("completed", "completed"),
                    ("settled", "settled"),
                    ("cancelled", "cancelled"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="productorder",
            index=models.Index(fields=["store", "status"], name="idx_porder_store_status"),
        ),
        migrations.AddField(
            model_name="productshipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="commerce.productorder",
            ),
        ),
    ]
