# Generated by Django 5.2.15 on 2026-06-06 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0005_shipment_state_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="blockchain_network",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("buyer_user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "requested"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("refunded", "refunded"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("requested_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(max_length=20)),
                ("admin_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="commerce.productorder",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_refund_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order", "status"], name="idx_refund_order_status")
                ],
            },
        ),
    ]
