# Generated by Django 5.2.15 on 2026-06-07 05:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiftCatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("emoji", models.CharField(blank=True, max_length=16)),
                ("icon_url", models.URLField(blank=True)),
                ("animation_url", models.URLField(blank=True)),
                ("preset_amount", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("preset_currency", models.CharField(default="MP", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "content_gift_catalog_item",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="GiftTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("sender_id", models.UUIDField(db_index=True)),
                ("receiver_id", models.UUIDField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("video", "video"),
                            ("drama_series", "drama_series"),
                            ("live_stream", "live_stream"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(max_length=20)),
                ("payment_method", models.CharField(max_length=20)),
                ("gift_code", models.TextField(blank=True)),
                ("sender_wallet_ledger_id", models.UUIDField(blank=True, null=True)),
                ("receiver_wallet_ledger_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "content_gift_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender_id", "created_at"], name="idx_gift_sender_created"
                    ),
                    models.Index(
                        fields=["receiver_id", "created_at"], name="idx_gift_receiver_created"
                    ),
                    models.Index(
                        fields=["target_type", "target_id", "created_at"],
                        name="idx_gift_target_created",
                    ),
                ],
            },
        ),
    ]
