# Generated by Django 5.2.15 on 2026-06-05 02:27

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEventDLQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                ("failure_history", models.JSONField(default=list)),
                ("moved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
            ],
            options={
                "db_table": "outbox_event_dlq",
                "ordering": ["-moved_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=128)),
                ("event_version", models.PositiveSmallIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("dispatched", "dispatched"),
                            ("processed", "processed"),
                            ("failed", "failed"),
                            ("dlq", "dlq"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "outbox_event",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "available_at"], name="idx_outbox_pending"),
                    models.Index(
                        fields=["event_type", "created_at"], name="idx_outbox_type_created"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_type", "idempotency_key"), name="outbox_idempotency_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEventHandlerAck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handler_name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handler_acks",
                        to="events.outboxevent",
                    ),
                ),
            ],
            options={
                "db_table": "outbox_event_handler_ack",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "handler_name"), name="outbox_ack_unique"
                    )
                ],
            },
        ),
    ]
