# Generated by Django 5.2.15 on 2026-06-07 04:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DramaCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_drama_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DramaSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("total_episodes", models.PositiveIntegerField(default=0)),
                ("free_episodes", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series",
                        to="content_drama.dramacategory",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_series",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DramaEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("episode_no", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "unlock_type",
                    models.CharField(
                        choices=[
                            ("free", "free"),
                            ("meow_points", "meow_points"),
                            ("meow_credit", "meow_credit"),
                            ("membership", "membership"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("points_price", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("credits_price", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("playback_url", models.URLField(blank=True)),
                ("hls_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="content_drama.dramaseries",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_episode",
                "ordering": ["episode_no"],
            },
        ),
        migrations.CreateModel(
            name="DramaUnlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("unlock_type", models.CharField(max_length=20)),
                ("ledger_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocks",
                        to="content_drama.dramaepisode",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_unlock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dramaseries",
            index=models.Index(
                fields=["is_active", "created_at"], name="idx_series_active_created"
            ),
        ),
        migrations.AddIndex(
            model_name="dramaseries",
            index=models.Index(
                fields=["owner_user_id", "created_at"], name="idx_series_owner_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaepisode",
            constraint=models.UniqueConstraint(
                fields=("series", "episode_no"), name="uq_episode_series_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaunlock",
            constraint=models.UniqueConstraint(
                fields=("user_id", "episode"), name="uq_unlock_user_episode"
            ),
        ),
    ]
