# Generated by Django 5.2.15 on 2026-06-07 04:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_drama", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DramaComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("content", models.TextField()),
                ("reply_count", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="content_drama.dramacomment",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content_drama.dramaseries",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_comment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["series", "parent", "created_at"], name="idx_dcomment_series_parent"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DramaFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="content_drama.dramaseries",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_favorite",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "series"), name="uq_favorite_user_series"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DramaSeriesView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=200)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="content_drama.dramaseries",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_series_view",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("dedup_key",), name="uq_drama_view_dedup")
                ],
            },
        ),
        migrations.CreateModel(
            name="DramaWatchProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("progress_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="content_drama.dramaepisode",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="content_drama.dramaseries",
                    ),
                ),
            ],
            options={
                "db_table": "content_drama_watch_progress",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "series"), name="uq_progress_user_series"
                    )
                ],
            },
        ),
    ]
