# Generated by Django 5.2.15 on 2026-06-05 04:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("business_kind", models.CharField(max_length=32)),
                ("business_ref_id", models.UUIDField()),
                ("user_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "pending_payment"),
                            ("authorized", "authorized"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                            ("expired", "expired"),
                            ("refunding", "refunding"),
                            ("refunded", "refunded"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("payment_provider", models.CharField(max_length=20)),
                ("blockchain_network", models.CharField(blank=True, max_length=20)),
                ("provider_intent_id", models.CharField(blank=True, max_length=255)),
                ("pay_to_address", models.CharField(blank=True, max_length=255)),
                ("expected_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("expected_currency", models.CharField(max_length=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("refund_reason", models.TextField(blank=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "db_table": "payments_order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="idx_order_status_created"),
                    models.Index(
                        fields=["business_kind", "business_ref_id"], name="idx_order_business_ref"
                    ),
                    models.Index(fields=["provider_intent_id"], name="idx_order_intent"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("signature_valid", models.BooleanField(default=False)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "payments_webhook_event",
                "ordering": ["-created_at"],
                "unique_together": {("provider", "event_id")},
            },
        ),
    ]
